# Generated by Django 3.2.9 on 2022-02-14 16:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
from expos.models import DateTimeWithoutTZField, AutoUUIDField


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etl_job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTyped',
            fields=[
                ('source_id', models.TextField()),
                ('attach', models.JSONField()),
                ('heading', models.TextField()),
                ('options', models.JSONField()),
                ('type', models.TextField()),
                ('sub_type', models.TextField()),
                ('external_created_at', DateTimeWithoutTZField()),
                ('external_updated_at', DateTimeWithoutTZField()),
                ('created_at', DateTimeWithoutTZField(default=datetime.datetime.now)),
                ('updated_at', DateTimeWithoutTZField(default=datetime.datetime.now)),
                ('id', AutoUUIDField(editable=False, primary_key=True, serialize=False)),
                ('job_id', models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, to='etl_job.etljob')),
            ],
            options={
                'db_table': 'airflow"."question_typed',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='QuestionStaged',
            fields=[
                ('source_id', models.TextField()),
                ('heading', models.TextField()),
                ('options', models.JSONField()),
                ('type', models.TextField()),
                ('sub_type', models.TextField()),
                ('external_created_at', DateTimeWithoutTZField()),
                ('external_updated_at', DateTimeWithoutTZField()),
                ('created_at', DateTimeWithoutTZField(default=datetime.datetime.now)),
                ('updated_at', DateTimeWithoutTZField(default=datetime.datetime.now)),
                ('id', AutoUUIDField(editable=False, primary_key=True, serialize=False)),
                ('job_id', models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, to='etl_job.etljob')),
            ],
            options={
                'db_table': 'airflow"."question_staged',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='QuestionRaw',
            fields=[
                ('source_id', models.TextField(blank=True, null=True)),
                ('attach', models.TextField(blank=True, null=True)),
                ('heading', models.TextField(blank=True, null=True)),
                ('options', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('sub_type', models.TextField(blank=True, null=True)),
                ('external_created_at', models.TextField(blank=True, null=True)),
                ('external_updated_at', models.TextField(blank=True, null=True)),
                ('created_at', DateTimeWithoutTZField(default=datetime.datetime.now)),
                ('updated_at', DateTimeWithoutTZField(default=datetime.datetime.now)),
                ('id', AutoUUIDField(editable=False, primary_key=True, serialize=False)),
                ('job_id', models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, to='etl_job.etljob')),
            ],
            options={
                'db_table': 'airflow"."question_raw',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='QuestionConform',
            fields=[
                ('source_id', models.TextField()),
                ('attach', models.JSONField()),
                ('heading', models.TextField()),
                ('options', models.JSONField()),
                ('type', models.TextField()),
                ('sub_type', models.TextField()),
                ('external_created_at', DateTimeWithoutTZField()),
                ('external_updated_at', DateTimeWithoutTZField()),
                ('created_at', DateTimeWithoutTZField(default=datetime.datetime.now)),
                ('updated_at', DateTimeWithoutTZField(default=datetime.datetime.now)),
                ('id', AutoUUIDField(editable=False, primary_key=True, serialize=False)),
                ('job_id', models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, to='etl_job.etljob')),
            ],
            options={
                'db_table': 'airflow"."question_conform',
                'managed': True,
            },
        ),
    ]
