# Generated by Django 3.2.9 on 2022-02-14 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etl_job', '0001_initial'),
        ('answer', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveystaged',
            name='customer_id',
            field=models.ForeignKey(db_column='customer_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='customer.customerstaged'),
        ),
        migrations.AddField(
            model_name='surveystaged',
            name='job_id',
            field=models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, to='etl_job.etljob'),
        ),
    ]
