# Generated by Django 3.2.9 on 2021-12-14 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0001_initial'),
        ('question', '0001_initial'),
        ('answer', '0002_initial'),
        ('etl_job', '0004_create_find_question_id_from_portals_procedure'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfevaluationstaged',
            name='vendor_id',
            field=models.ForeignKey(db_column='vendor_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='vendor.vendorstaged'),
        ),
        migrations.AddField(
            model_name='selfevaluationconform',
            name='job_id',
            field=models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, to='etl_job.etljob'),
        ),
        migrations.AddField(
            model_name='answertyped',
            name='job_id',
            field=models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, to='etl_job.etljob'),
        ),
        migrations.AddField(
            model_name='answerstaged',
            name='job_id',
            field=models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, to='etl_job.etljob'),
        ),
        migrations.AddField(
            model_name='answerstaged',
            name='question_id',
            field=models.ForeignKey(db_column='question_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='question.questionstaged'),
        ),
        migrations.AddField(
            model_name='answerraw',
            name='job_id',
            field=models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, to='etl_job.etljob'),
        ),
        migrations.AddField(
            model_name='answerconform',
            name='job_id',
            field=models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, to='etl_job.etljob'),
        ),
    ]
