# Generated by Django 3.2.9 on 2022-02-14 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl_job', '0001_initial'),
        ('vendor', '0001_initial'),
        ('customer', '0002_initial'),
        ('answer', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SelfEvaluationConform',
            new_name='SurveyConform',
        ),
        migrations.RenameModel(
            old_name='SelfEvaluationStaged',
            new_name='SurveyStaged',
        ),
        migrations.RenameField(
            model_name='answerconform',
            old_name='self_evaluation_id',
            new_name='survey_id',
        ),
        migrations.AlterModelTable(
            name='surveyconform',
            table='survey_conform',
        ),
        migrations.AlterModelTable(
            name='surveystaged',
            table='survey_staged',
        ),
    ]
