# Generated by Django 3.2.9 on 2022-01-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0004_selfevaluationfailedinserts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selfevaluationfailedinserts',
            name='customer_rut',
        ),
        migrations.RemoveField(
            model_name='selfevaluationfailedinserts',
            name='vendor_rut',
        ),
        migrations.AlterField(
            model_name='selfevaluationfailedinserts',
            name='customer_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='selfevaluationfailedinserts',
            name='customer_source_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='selfevaluationfailedinserts',
            name='vendor_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='selfevaluationfailedinserts',
            name='vendor_source_id',
            field=models.TextField(null=True),
        ),
    ]
