FROM reigncl/airflow:2.3.1-python3.9-onbuild

USER root

RUN sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 467B942D3A79BD29

RUN apt-get update \
  && apt-get install -y --no-install-recommends less unzip wget vim zip \
  && apt-get autoremove -yqq --purge \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

USER airflow

RUN mkdir -p data

COPY ./dags ${AIRFLOW_HOME}/dags
COPY ./include ${AIRFLOW_HOME}/include
COPY ./plugins ${AIRFLOW_HOME}/plugins
COPY ./requirements*.txt ./

RUN pip install --upgrade pip \
    && pip install --no-cache-dir \
      -r requirements.txt \
      -r requirements-dev.txt
