# Generated by Django 3.2.9 on 2021-12-09 13:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
import gac.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etl_job', '0004_create_find_question_id_from_portals_procedure'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorTypeTyped',
            fields=[
                ('source_id', models.IntegerField()),
                ('name', models.TextField()),
                ('created_at', gac.models.DateTimeWithoutTZField(default=datetime.datetime.now)),
                ('updated_at', gac.models.DateTimeWithoutTZField(default=datetime.datetime.now)),
                ('id', gac.models.AutoUUIDField(editable=False, primary_key=True, serialize=False)),
                ('job_id', models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, to='etl_job.etljob')),
            ],
            options={
                'db_table': 'airflow"."vendor_type_typed',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VendorTypeRaw',
            fields=[
                ('source_id', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('created_at', gac.models.DateTimeWithoutTZField(default=datetime.datetime.now)),
                ('updated_at', gac.models.DateTimeWithoutTZField(default=datetime.datetime.now)),
                ('id', gac.models.AutoUUIDField(editable=False, primary_key=True, serialize=False)),
                ('job_id', models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, to='etl_job.etljob')),
            ],
            options={
                'db_table': 'airflow"."vendor_type_raw',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VendorTypeConform',
            fields=[
                ('source_id', models.IntegerField()),
                ('name', models.TextField()),
                ('created_at', gac.models.DateTimeWithoutTZField(default=datetime.datetime.now)),
                ('updated_at', gac.models.DateTimeWithoutTZField(default=datetime.datetime.now)),
                ('id', gac.models.AutoUUIDField(editable=False, primary_key=True, serialize=False)),
                ('job_id', models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, to='etl_job.etljob')),
            ],
            options={
                'db_table': 'airflow"."vendor_type_conform',
                'managed': True,
            },
        ),
    ]
