# Generated by Django 3.2.9 on 2022-02-07 17:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
import expos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etl_job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChiefConform',
            fields=[
                ('source_id', models.IntegerField()),
                ('code', models.TextField(blank=True, null=True)),
                ('name', models.TextField()),
                ('location', models.TextField(blank=True, null=True)),
                ('rut', models.TextField()),
                ('plant_id', models.IntegerField()),
                ('role', models.TextField(blank=True, null=True)),
                ('unit', models.TextField(blank=True, null=True)),
                ('created_at', expos.models.DateTimeWithoutTZField(default=datetime.datetime.now)),
                ('updated_at', expos.models.DateTimeWithoutTZField(default=datetime.datetime.now)),
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'airflow"."chief_conform',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ChiefPlantRaw',
            fields=[
                ('chief_id', models.TextField(blank=True, null=True)),
                ('chief_code', models.TextField(blank=True, null=True)),
                ('chief_name', models.TextField(blank=True, null=True)),
                ('chief_location', models.TextField(blank=True, null=True)),
                ('chief_rut', models.TextField(blank=True, null=True)),
                ('plant_id', models.TextField(blank=True, null=True)),
                ('role', models.TextField(blank=True, null=True)),
                ('chief_unit', models.TextField(blank=True, null=True)),
                ('created_at', expos.models.DateTimeWithoutTZField(default=datetime.datetime.now)),
                ('updated_at', expos.models.DateTimeWithoutTZField(default=datetime.datetime.now)),
                ('id', expos.models.AutoUUIDField(editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'airflow"."chief_plant_raw',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ChiefPlantTyped',
            fields=[
                ('chief_id', models.IntegerField()),
                ('chief_code', models.TextField(blank=True, null=True)),
                ('chief_name', models.TextField()),
                ('chief_location', models.TextField(blank=True, null=True)),
                ('chief_rut', models.TextField()),
                ('plant_id', models.IntegerField()),
                ('role', models.TextField(blank=True, null=True)),
                ('chief_unit', models.TextField(blank=True, null=True)),
                ('created_at', expos.models.DateTimeWithoutTZField(default=datetime.datetime.now)),
                ('updated_at', expos.models.DateTimeWithoutTZField(default=datetime.datetime.now)),
                ('id', expos.models.AutoUUIDField(editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'airflow"."chief_plant_typed',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ChiefStaged',
            fields=[
                ('source_id', models.IntegerField()),
                ('code', models.TextField(blank=True, null=True)),
                ('name', models.TextField()),
                ('location', models.TextField(blank=True, null=True)),
                ('rut', models.TextField()),
                ('role', models.TextField(blank=True, null=True)),
                ('unit', models.TextField(blank=True, null=True)),
                ('created_at', expos.models.DateTimeWithoutTZField(default=datetime.datetime.now)),
                ('updated_at', expos.models.DateTimeWithoutTZField(default=datetime.datetime.now)),
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('job_id', models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, to='etl_job.etljob')),
            ],
            options={
                'db_table': 'airflow"."chief_staged',
                'managed': True,
            },
        ),
    ]
