hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  metrics:
    cpu:
      targetAverageUtilization: 40
    memory:
      targetAverageUtilization: 70

ingress:
  hosts:
    - airflow2.production.embonorservices.cl

env:
  - name: STAGE
    value: production

secret:
  - envName: "GAC_SQL_CONN_URI"
    secretName: "airflow-envars"
    secretKey: "GAC_SQL_CONN_URI"
  - envName: "EMBONOR_SERVICES_BASE_URL"
    secretName: "airflow-envars"
    secretKey: "EMBONOR_SERVICES_BASE_URL"
  - envName: "EMBONOR_PG_CONN_URI"
    secretName: "airflow-envars"
    secretKey: "EMBONOR_PG_CONN_URI"
  - envName: "EMBONOR_MONGO_CONN_URI"
    secretName: "airflow-envars"
    secretKey: "EMBONOR_MONGO_CONN_URI"
