registry:
  secretName: airflow-dockercfg
executor: "CeleryExecutor"
data:
  metadataSecretName: airflow-metadata
  resultBackendSecretName: airflow-result-backend
dags:
  gitSync:
    enabled: false
redis:
  enabled: true
flower:
  enabled: false
postgresql:
  enabled: false
pgbouncer:
  enabled: true
webserverSecretKeySecretName: airflow-webserver-secret-key-custom
webserver:
  defaultUser:
    enabled: true
    role: Admin
    username: admin
    email: admin@example.com
    firstName: admin
    lastName: user
    password: admin
  args: ["airflow", "webserver"]
  livenessProbe:
    initialDelaySeconds: 35
  readinessProbe:
    initialDelaySeconds: 30
workers:
  persistence:
    fixPermissions: true
  resources:
    limits:
     cpu: 200m
     memory: 3072Mi
    requests:
     cpu: 150m
     memory: 1536Mi
  extraVolumes:
    - name: connections
      secret:
        secretName: airflow-connections
        optional: false
    - name: variables
      secret:
        secretName: airflow-variables
        optional: false
  extraVolumeMounts:
    - name: connections
      mountPath: "/opt/airflow/connections"
      readOnly: true
    - name: variables
      mountPath: "/opt/airflow/variables"
      readOnly: true
scheduler:
  extraVolumes:
    - name: connections
      secret:
        secretName: airflow-connections
        optional: false
    - name: variables
      secret:
        secretName: airflow-variables
        optional: false
  extraVolumeMounts:
    - name: connections
      mountPath: "/opt/airflow/connections"
      readOnly: true
    - name: variables
      mountPath: "/opt/airflow/variables"
      readOnly: true
ingress:
  enabled: true
  web:
    annotations:
      #{} #To use ALB Ingress, uncomment this line, comment the next one and uncomment the corresponding annotations
      kubernetes.io/ingress.class: traefik
    path: /
config:
  core:
    sql_alchemy_connect_args: __config.keepalives.keepalive_kwargs
    dagbag_import_timeout: 120.0
  api:
    auth_backend: airflow.api.auth.backend.basic_auth
  scheduler:
    scheduler_health_check_threshold: '120'
    min_file_process_interval: '60'
statsd:
  enabled: false
env:
  - name: AIRFLOW__SECRETS__BACKEND
    value: reign_airflow_utils.secret_backends.FileSystemSecretsBackend
  - name: AIRFLOW__SECRETS__BACKEND_KWARGS
    value: |2
      {"connections_path": "/opt/airflow/connections", "variables_path": "/opt/airflow/variables"}
