ingress:
  web:
    hosts:
      - airflow2.develop.embonorservices.cl

env:
  - name: STAGE
    value: development
  - name: ML_MAXERIENCE_BASE_URL
    value: https://portal-stg1.maxerience.com/IrHandler

secret:
  - envName: "EMBONOR_MONGO_CONN_URI"
    secretName: "airflow-envars"
    secretKey: "EMBONOR_MONGO_CONN_URI"
  - envName: "EMBONOR_PG_CONN_URI"
    secretName: "airflow-envars"
    secretKey: "EMBONOR_PG_CONN_URI"
  - envName: "EMBONOR_SERVICES_BASE_URL"
    secretName: "airflow-envars"
    secretKey: "EMBONOR_SERVICES_BASE_URL"
  - envName: "GAC_SQL_CONN_URI"
    secretName: "airflow-envars"
    secretKey: "GAC_SQL_CONN_URI"
  - envName: "PRE_AUTHENTICATED_REQUESTS_URL"
    secretName: "airflow-envars"
    secretKey: "PRE_AUTHENTICATED_REQUESTS_URL"
  - envName: "AUTH_USER"
    secretName: "airflow-envars"
    secretKey: "AUTH_USER"
  - envName: "AUTH_PASS"
    secretName: "airflow-envars"
    secretKey: "AUTH_PASS"
  - envName: "OCI_USER"
    secretName: "airflow-envars"
    secretKey: "OCI_USER"
  - envName: "OCI_KEY"
    secretName: "airflow-envars"
    secretKey: "OCI_KEY"
  - envName: "OCI_FINGERPRINT"
    secretName: "airflow-envars"
    secretKey: "OCI_FINGERPRINT"
  - envName: "OCI_TENANCY"
    secretName: "airflow-envars"
    secretKey: "OCI_TENANCY"
  - envName: "OCI_REGION"
    secretName: "airflow-envars"
    secretKey: "OCI_REGION"
