registry:
  secretName: airflow-dockercfg
executor: "CeleryExecutor"
data:
  metadataSecretName: airflow-metadata
  resultBackendSecretName: airflow-result-backend
dags:
  gitSync:
    enabled: false
redis:
  enabled: true
flower:
  enabled: false
postgresql:
  enabled: false
webserver:
  defaultUser:
    enabled: true
    role: Admin
    username: admin
    email: admin@example.com
    firstName: admin
    lastName: user
    password: admin
ingress:
  enabled: true
  web:
    annotations:
      kubernetes.io/ingress.class: traefik
    path: /
    hosts:
      - airflow2.develop.embonorservices.cl
config:
  api:
    auth_backend: airflow.api.auth.backend.basic_auth
