registry:
  secretName: airflow-dockercfg
executor: "CeleryExecutor"
data:
  metadataSecretName: airflow-metadata
  resultBackendSecretName: airflow-result-backend
dags:
  gitSync:
    enabled: false
redis:
  enabled: true
flower:
  enabled: false
postgresql:
  enabled: false
pgbouncer:
  enabled: true
webserverSecretKeySecretName: airflow-webserver-secret-key-custom
webserver:
  defaultUser:
    enabled: true
    role: Admin
    username: admin
    email: admin@example.com
    firstName: admin
    lastName: user
    password: admin
  args: ["airflow", "webserver"]
  livenessProbe:
    initialDelaySeconds: 35
  readinessProbe:
    initialDelaySeconds: 30
  extraVolumes:
    - name: variables
      secret:
        secretName: airflow-variables
        optional: false
  extraVolumeMounts:
    - name: variables
      mountPath: "/opt/airflow/variables"
      readOnly: true
workers:
  persistence:
    fixPermissions: true
  resources:
    limits:
     cpu: 200m
     memory: 3072Mi
    requests:
     cpu: 150m
     memory: 1536Mi
  extraVolumes:
    - name: connections
      secret:
        secretName: airflow-connections
        optional: false
    - name: variables
      secret:
        secretName: airflow-variables
        optional: false
    - name: registered-projects
      configMap:
        name: airflow-registered-projects
    - name: dags-volume
      emptyDir: {}
    - name: include-volume
      emptyDir: {}
  extraVolumeMounts:
    - name: connections
      mountPath: "/opt/airflow/connections"
      readOnly: true
    - name: variables
      mountPath: "/opt/airflow/variables"
      readOnly: true
    - name: registered-projects
      mountPath: "/opt/airflow/registered_projects"
      readOnly: true
    - name: dags-volume
      mountPath: "/opt/airflow/dags"
    - name: include-volume
      mountPath: "/opt/airflow/include"
  extraContainers:
    - name: gitsync-sidecar
      image: reigncl/airflow-gitsync-sidecar:latest
      imagePullPolicy: Always
      command: ["npm"]
      args: ["start"]
      readinessProbe:
        httpGet:
          path: /health
          port: git-sync-sidecar
        initialDelaySeconds: 9
      livenessProbe:
        httpGet:
          path: /health
          port: git-sync-sidecar
        initialDelaySeconds: 6
      ports:
        - name: git-sync-sidecar
          containerPort: 3030
      volumeMounts:
        - name: registered-projects
          mountPath: "/registered_projects"
          readOnly: true
        - name: dags-volume
          mountPath: "/dags"
        - name: include-volume
          mountPath: "/include"
      envFrom:
        - secretRef:
            name: airflow-sidecar-envars
scheduler:
  extraVolumes:
    - name: connections
      secret:
        secretName: airflow-connections
        optional: false
    - name: variables
      secret:
        secretName: airflow-variables
        optional: false
    - name: registered-projects
      configMap:
        name: airflow-registered-projects
  extraVolumeMounts:
    - name: connections
      mountPath: "/opt/airflow/connections"
      readOnly: true
    - name: variables
      mountPath: "/opt/airflow/variables"
      readOnly: true
    - name: registered-projects
      mountPath: "/opt/airflow/registered_projects"
      readOnly: true
  extraContainers:
    - name: gitsync-sidecar
      image: reigncl/airflow-gitsync-sidecar:latest
      imagePullPolicy: Always
      command: [ "npm" ]
      args: [ "start" ]
      readinessProbe:
        httpGet:
          path: /health
          port: git-sync-sidecar
        initialDelaySeconds: 9
      livenessProbe:
        httpGet:
          path: /health
          port: git-sync-sidecar
        initialDelaySeconds: 6
      ports:
        - name: git-sync-sidecar
          containerPort: 3030
      volumeMounts:
        - name: registered-projects
          mountPath: "/registered_projects"
          readOnly: true
        - name: dags-volume
          mountPath: "/dags"
        - name: include-volume
          mountPath: "/include"
      envFrom:
        - secretRef:
            name: airflow-sidecar-envars
ingress:
  enabled: true
  web:
    annotations:
      #{} #To use ALB Ingress, uncomment this line, comment the next one and uncomment the corresponding annotations
      kubernetes.io/ingress.class: traefik
    path: /
config:
  core:
    sql_alchemy_connect_args: __config.keepalives.keepalive_kwargs
    dagbag_import_timeout: 120.0
  api:
    auth_backend: airflow.api.auth.backend.basic_auth
  scheduler:
    scheduler_health_check_threshold: '120'
    min_file_process_interval: '60'
  secrets:
    backend: reign_airflow_utils.secret_backends.FileSystemSecretsBackend
    backend_kwargs: |2
      {"connections_path": "/opt/airflow/connections", "variables_path": "/opt/airflow/variables"}
statsd:
  enabled: false
