registry:
  secretName: airflow-dockercfg
executor: "CeleryExecutor"
data:
  metadataSecretName: airflow-metadata
  resultBackendSecretName: airflow-result-backend
dags:
  gitSync:
    enabled: false
redis:
  enabled: true
flower:
  enabled: false
postgresql:
  enabled: false
pgbouncer:
  enabled: true
webserverSecretKeySecretName: airflow-webserver-secret-key-custom
webserver:
  defaultUser:
    enabled: true
    role: Admin
    username: admin
    email: admin@example.com
    firstName: admin
    lastName: user
    password: admin
  args: ["bash", "-c", "sh /opt/airflow/include/db/init.sh && python /opt/airflow/dags/config/init.py && airflow webserver"]
workers:
  persistence:
    fixPermissions: true
ingress:
  enabled: true
  web:
    annotations:
      #{} #To use ALB Ingress, uncomment this line, comment the next one and uncomment the corresponding annotations
      kubernetes.io/ingress.class: traefik
    path: /
config:
  api:
    auth_backend: airflow.api.auth.backend.basic_auth
statsd:
  enabled: false
env:
  - name: "MRR_MAXERIENCE_REST_BASE_URL"
    value: "https://irclientdataexport.blob.core.windows.net/"
