registry:
  secretName: airflow-dockercfg
executor: "CeleryExecutor"
data:
  metadataSecretName: airflow-metadata
  resultBackendSecretName: airflow-result-backend
dags:
  gitSync:
    enabled: false
redis:
  enabled: true
flower:
  enabled: false
postgresql:
  enabled: false
webserver:
  defaultUser:
    enabled: true
    role: Admin
    username: admin
    email: admin@example.com
    firstName: admin
    lastName: user
    password: admin
  args: ["bash", "-c", "sh /opt/airflow/include/db/init.sh && python /opt/airflow/dags/config/init.py && airflow webserver"]
workers:
  persistence:
    # Enable persistent volumes
    enabled: true
    # Volume size for worker StatefulSet
    size: 100Gi
    # If using a custom storageClass, pass name ref to all statefulSets here
    storageClassName:
    # Execute init container to chown log directory.
    # This is currently only needed in kind, due to usage
    # of local-path provisioner.
    fixPermissions: true
ingress:
  enabled: true
  web:
    annotations:
      kubernetes.io/ingress.class: traefik
    path: /
    hosts:
      - airflow2.develop.embonorservices.cl
config:
  api:
    auth_backend: airflow.api.auth.backend.basic_auth
statsd:
  enabled: false
