ingress:
  web:
    hosts:
      - airflow2.production.embonorservices.cl

env:
  - name: STAGE
    value: production
  - name: ML_MAXERIENCE_BASE_URL
    value: https://portal.visioniot.net/IrHandler
  - name: MRR_MAXERIENCE_REST_BASE_URL
    value: https://irclientdataexport.blob.core.windows.net/
  - name: SLACK_ETL_SUCCESS_CHANNEL
    value: C030CACGC1E
  - name: SURVEYS_SERVICE_BASE_URL
    value: https://api.production.embonorservices.cl/surveys-service
secret:
  - envName: "EXPOS_SQL_CONN_URI"
    secretName: "airflow-envars"
    secretKey: "EXPOS_SQL_CONN_URI"
  - envName: "EMBONOR_SERVICES_BASE_URL"
    secretName: "airflow-envars"
    secretKey: "EMBONOR_SERVICES_BASE_URL"
  - envName: "EMBONOR_PG_CONN_URI"
    secretName: "airflow-envars"
    secretKey: "EMBONOR_PG_CONN_URI"
  - envName: "EMBONOR_MONGO_CONN_URI"
    secretName: "airflow-envars"
    secretKey: "EMBONOR_MONGO_CONN_URI"
  - envName: "PRE_AUTHENTICATED_REQUESTS_URL"
    secretName: "airflow-envars"
    secretKey: "PRE_AUTHENTICATED_REQUESTS_URL"
  - envName: "AUTH_USER"
    secretName: "airflow-envars"
    secretKey: "AUTH_USER"
  - envName: "AUTH_PASS"
    secretName: "airflow-envars"
    secretKey: "AUTH_PASS"
  - envName: "OCI_USER"
    secretName: "airflow-envars"
    secretKey: "OCI_USER"
  - envName: "OCI_KEY"
    secretName: "airflow-envars"
    secretKey: "OCI_KEY"
  - envName: "OCI_FINGERPRINT"
    secretName: "airflow-envars"
    secretKey: "OCI_FINGERPRINT"
  - envName: "OCI_TENANCY"
    secretName: "airflow-envars"
    secretKey: "OCI_TENANCY"
  - envName: "OCI_REGION"
    secretName: "airflow-envars"
    secretKey: "OCI_REGION"
  - envName: "ML_MAXERIENCE_USER"
    secretName: "airflow-envars"
    secretKey: "ML_MAXERIENCE_USER"
  - envName: "ML_MAXERIENCE_PASS"
    secretName: "airflow-envars"
    secretKey: "ML_MAXERIENCE_PASS"
  - envName: "SLACK_SUCCESS_CHANNEL_URL"
    secretName: "airflow-envars"
    secretKey: "SLACK_SUCCESS_CHANNEL_URL"
  - envName: "SLACK_FAILURE_CHANNEL_URL"
    secretName: "airflow-envars"
    secretKey: "SLACK_FAILURE_CHANNEL_URL"
  - envName: "MRR_SAS_KEY"
    secretName: "airflow-envars"
    secretKey: "MRR_SAS_KEY"
  - envName: "SLACK_EXPOS_BOT_TOKEN"
    secretName: "airflow-envars"
    secretKey: "SLACK_EXPOS_BOT_TOKEN"
  - envName: "SPCL_S3_CONN_URI"
    secretName: "airflow-envars"
    secretKey: "SPCL_S3_CONN_URI"
