# Generated by Django 3.2.9 on 2021-12-03 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl_job', '0002_create_clean_answer_mongo_procedure'),
    ]

    operations = [
        migrations.RunSQL(sql="""
            CREATE OR REPLACE FUNCTION clean_survey_collection_ids(in_array jsonb)
            RETURNS jsonb AS $$
            DECLARE
                portals jsonb := in_array;
                portal jsonb;
                new_portals jsonb;
                portal_as_str text;

                pages jsonb;
                page jsonb;
                new_pages jsonb;

                questions jsonb;
                question jsonb;
                new_questions jsonb;
            BEGIN
                new_portals := jsonb_build_array();
                FOR portal IN SELECT * FROM jsonb_array_elements(portals)
                LOOP
                    new_pages := jsonb_build_array();

                    portal_as_str := portal :: text;
                    portal_as_str := replace(portal_as_str, '_id', 'id');
                    portal := portal_as_str :: jsonb;
                    pages := portal->'pages';
                    FOR page IN SELECT * FROM jsonb_array_elements(pages)
                    LOOP
                        new_questions := jsonb_build_array();
                        questions := page->'questions';
                        FOR question IN SELECT * FROM jsonb_array_elements(questions)
                        LOOP
                            new_questions := new_questions || (question || jsonb_build_object(
                                'id', question->'id'->>'$oid'
                            ));
                        END LOOP;
                        new_pages := new_pages || (page || jsonb_build_object(
                            'id', page->'id'->>'$oid',
                            'questions', new_questions
                        ));
                    END LOOP;
                    new_portals := new_portals || (portal || jsonb_build_object(
                        'id', portal->'id'->>'$oid',
                        'pages', new_pages
                    ));
                END LOOP;
                RETURN new_portals;
            END;
            $$ LANGUAGE plpgsql;
        """)
    ]
