# Generated by Django 3.2.9 on 2021-12-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_plant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorplantconform',
            name='vendor_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorplantraw',
            name='vendor_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorplanttyped',
            name='vendor_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
