# Generated by Django 3.2.9 on 2022-03-21 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '__first__'),
        ('customer', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerstaged',
            name='cluster',
        ),
        migrations.AddField(
            model_name='customerstaged',
            name='cluster_id',
            field=models.ForeignKey(db_column='cluster_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='cluster.clusterstaged'),
        ),
    ]
