# Generated by Django 3.2.9 on 2022-06-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyconform',
            name='source_survey_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='surveystaged',
            name='source_survey_id',
            field=models.TextField(null=True),
        ),
    ]
