# Generated by Django 3.2.9 on 2021-12-03 19:57

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import gac.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etl_job', '0004_create_find_question_id_from_portals_procedure'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfEvaluationConform',
            fields=[
                ('source_id', models.TextField()),
                ('skips_survey', models.BooleanField()),
                ('vendor_id', models.IntegerField()),
                ('customer_id', models.IntegerField()),
                ('external_created_at', gac.models.DateTimeWithoutTZField()),
                ('created_at', gac.models.DateTimeWithoutTZField(default=datetime.datetime.now)),
                ('updated_at', gac.models.DateTimeWithoutTZField(default=datetime.datetime.now)),
                ('id', gac.models.AutoUUIDField(editable=False, primary_key=True, serialize=False)),
                ('job_id', models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, to='etl_job.etljob')),
            ],
            options={
                'db_table': 'airflow"."self_evaluation_conform',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AnswerTyped',
            fields=[
                ('source_id', models.TextField()),
                ('survey_id', models.TextField()),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('skips_survey', models.BooleanField()),
                ('pollster_id', models.IntegerField()),
                ('surveyed_id', models.IntegerField()),
                ('external_created_at', gac.models.DateTimeWithoutTZField()),
                ('answers', models.JSONField()),
                ('created_at', gac.models.DateTimeWithoutTZField(default=datetime.datetime.now)),
                ('updated_at', gac.models.DateTimeWithoutTZField(default=datetime.datetime.now)),
                ('id', gac.models.AutoUUIDField(editable=False, primary_key=True, serialize=False)),
                ('job_id', models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, to='etl_job.etljob')),
            ],
            options={
                'db_table': 'airflow"."answer_typed',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AnswerRaw',
            fields=[
                ('source_id', models.TextField(blank=True, null=True)),
                ('survey_id', models.TextField(blank=True, null=True)),
                ('latitude', models.TextField(blank=True, null=True)),
                ('longitude', models.TextField(blank=True, null=True)),
                ('skips_survey', models.TextField(blank=True, null=True)),
                ('pollster_id', models.TextField(blank=True, null=True)),
                ('surveyed_id', models.TextField(blank=True, null=True)),
                ('external_created_at', models.TextField(blank=True, null=True)),
                ('answers', models.TextField(blank=True, null=True)),
                ('created_at', gac.models.DateTimeWithoutTZField(default=datetime.datetime.now)),
                ('updated_at', gac.models.DateTimeWithoutTZField(default=datetime.datetime.now)),
                ('id', gac.models.AutoUUIDField(editable=False, primary_key=True, serialize=False)),
                ('job_id', models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, to='etl_job.etljob')),
            ],
            options={
                'db_table': 'airflow"."answer_raw',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AnswerConform',
            fields=[
                ('source_id', models.TextField()),
                ('values', models.JSONField()),
                ('attachments', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('observations', models.TextField(null=True)),
                ('self_evaluation_id', models.UUIDField()),
                ('question_id', models.TextField()),
                ('created_at', gac.models.DateTimeWithoutTZField(default=datetime.datetime.now)),
                ('updated_at', gac.models.DateTimeWithoutTZField(default=datetime.datetime.now)),
                ('id', gac.models.AutoUUIDField(editable=False, primary_key=True, serialize=False)),
                ('job_id', models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, to='etl_job.etljob')),
            ],
            options={
                'db_table': 'airflow"."answer_conform',
                'managed': True,
            },
        ),
    ]
