# Generated by Django 3.2.9 on 2022-03-22 00:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
from expos.models import DateTimeWithoutTZField, AutoUUIDField


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etl_job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterStaged',
            fields=[
                ('name', models.TextField()),
                ('created_at', DateTimeWithoutTZField(default=datetime.datetime.now)),
                ('updated_at', DateTimeWithoutTZField(default=datetime.datetime.now)),
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('job_id', models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, to='etl_job.etljob')),
            ],
            options={
                'db_table': 'airflow"."cluster_staged',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClusterConform',
            fields=[
                ('name', models.TextField()),
                ('created_at', DateTimeWithoutTZField(default=datetime.datetime.now)),
                ('updated_at', DateTimeWithoutTZField(default=datetime.datetime.now)),
                ('id', AutoUUIDField(editable=False, primary_key=True, serialize=False)),
                ('job_id', models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, to='etl_job.etljob')),
            ],
            options={
                'db_table': 'airflow"."cluster_conform',
                'managed': True,
            },
        ),
    ]
