# Generated by Django 3.2.9 on 2021-12-03 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl_job', '0003_create_clean_survey_mongo_procedure'),
    ]

    operations = [
        migrations.RunSQL(sql="""
            CREATE OR REPLACE FUNCTION find_question_id_from_portals(in_array jsonb, id_to_find varchar)
            RETURNS varchar AS $$
            DECLARE
                portals jsonb := in_array;
                portal jsonb;

                pages jsonb;
                page jsonb;

                questions jsonb;
                question jsonb;

                found_id varchar;
            BEGIN
                FOR portal IN SELECT * FROM jsonb_array_elements(portals)
                LOOP

                    pages := portal->'pages';
                    FOR page IN SELECT * FROM jsonb_array_elements(pages)
                    LOOP
                        questions := page->'questions';
                        FOR question IN SELECT * FROM jsonb_array_elements(questions)
                        LOOP
                           IF question->>'id' = id_to_find THEN
                                found_id := question->'question'->>'$oid';
                                SELECT id INTO found_id FROM airflow.question_typed WHERE source_id = found_id;
                                RETURN found_id;
                            END IF;
                        END LOOP;

                    END LOOP;

                END LOOP;
                RAISE EXCEPTION 'Requested question_id not found: %s', id_to_find;
            END;
                $$ LANGUAGE plpgsql;
        """)
    ]
