# Generated by Django 3.2.9 on 2021-12-03 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl_job', '0003_create_clean_survey_mongo_procedure'),
    ]

    operations = [
        migrations.RunSQL(sql="""

        """)
    ]
