# Generated by Django 3.2.9 on 2022-02-14 16:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
from expos.models import DateTimeWithoutTZField, AutoUUIDField


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etl_job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorPlantTyped',
            fields=[
                ('vendor_id', models.IntegerField()),
                ('supervisor_id', models.IntegerField()),
                ('chief_rut', models.TextField()),
                ('plant_id', models.IntegerField()),
                ('vendor_name', models.TextField(blank=True, null=True)),
                ('created_at', DateTimeWithoutTZField(default=datetime.datetime.now)),
                ('updated_at', DateTimeWithoutTZField(default=datetime.datetime.now)),
                ('id', AutoUUIDField(editable=False, primary_key=True, serialize=False)),
                ('job_id', models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, to='etl_job.etljob')),
            ],
            options={
                'db_table': 'airflow"."vendor_plant_typed',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VendorPlantRaw',
            fields=[
                ('vendor_id', models.TextField(blank=True, null=True)),
                ('supervisor_id', models.TextField(blank=True, null=True)),
                ('chief_rut', models.TextField(blank=True, null=True)),
                ('plant_id', models.TextField(blank=True, null=True)),
                ('vendor_name', models.TextField(blank=True, null=True)),
                ('created_at', DateTimeWithoutTZField(default=datetime.datetime.now)),
                ('updated_at', DateTimeWithoutTZField(default=datetime.datetime.now)),
                ('id', AutoUUIDField(editable=False, primary_key=True, serialize=False)),
                ('job_id', models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, to='etl_job.etljob')),
            ],
            options={
                'db_table': 'airflow"."vendor_plant_raw',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VendorPlantConform',
            fields=[
                ('vendor_id', models.IntegerField()),
                ('supervisor_id', models.UUIDField()),
                ('plant_id', models.UUIDField()),
                ('vendor_name', models.TextField(blank=True, null=True)),
                ('created_at', DateTimeWithoutTZField(default=datetime.datetime.now)),
                ('updated_at', DateTimeWithoutTZField(default=datetime.datetime.now)),
                ('id', AutoUUIDField(editable=False, primary_key=True, serialize=False)),
                ('job_id', models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, to='etl_job.etljob')),
            ],
            options={
                'db_table': 'airflow"."vendor_plant_conform',
                'managed': True,
            },
        ),
    ]
