DROP TABLE IF EXISTS airflow.tmp_customer;

CREATE TABLE airflow.tmp_customer (
    id TEXT,
    priceList TEXT,
    name TEXT,
    dni TEXT,
    email TEXT,
    street TEXT,
    streetNumber TEXT,
    location TEXT,
    subLocation TEXT,
    phoneNumber TEXT,
    branchOffice TEXT,
    businessName TEXT,
    categoryName TEXT,
    categoryId TEXT,
    mainCategoryName TEXT,
    mainCategoryId TEXT,
    latitude TEXT,
    longitude TEXT,
    observations TEXT,
    creditAmount TEXT,
    creditBalance TEXT,
    appliesIVA TEXT,
    appliesIABA TEXT,
    appliesILA TEXT,
    dutyFreePriceList TEXT,
    plantId TEXT,
    zoneId TEXT,
    ruteId TEXT,
    territoryId TEXT,
    channelMkt TEXT,
    countrySpecific TEXT,
    geog TEXT,
    deletedAt TEXT,
    saleSystem TEXT,
    marketGroupId TEXT,
    marketChainId TEXT,
    creditBalanceCurrent TEXT,
    useSharedCredit TEXT
);
