# Generated by Django 3.2.9 on 2021-12-09 13:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
import gac.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_initial'),
        ('etl_job', '0004_create_find_question_id_from_portals_procedure'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorCustomerTyped',
            fields=[
                ('vendor_id', models.IntegerField()),
                ('customer_id', models.IntegerField()),
                ('start_date', models.DateField()),
                ('frequency', models.IntegerField()),
                ('priority', models.IntegerField()),
                ('created_at', gac.models.DateTimeWithoutTZField(default=datetime.datetime.now)),
                ('updated_at', gac.models.DateTimeWithoutTZField(default=datetime.datetime.now)),
                ('id', gac.models.AutoUUIDField(editable=False, primary_key=True, serialize=False)),
                ('job_id', models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, to='etl_job.etljob')),
            ],
            options={
                'db_table': 'airflow"."vendor_customer_typed',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VendorCustomerStaged',
            fields=[
                ('start_date', models.DateField()),
                ('frequency', models.IntegerField()),
                ('priority', models.IntegerField()),
                ('created_at', gac.models.DateTimeWithoutTZField(default=datetime.datetime.now)),
                ('updated_at', gac.models.DateTimeWithoutTZField(default=datetime.datetime.now)),
                ('id', gac.models.AutoUUIDField(editable=False, primary_key=True, serialize=False)),
                ('customer_id', models.ForeignKey(db_column='customer_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='customer.customerstaged')),
                ('job_id', models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, to='etl_job.etljob')),
                ('vendor_id', models.ForeignKey(db_column='vendor_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='vendor.vendorstaged')),
            ],
            options={
                'db_table': 'airflow"."vendor_customer_staged',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VendorCustomerRaw',
            fields=[
                ('vendor_id', models.TextField(blank=True, null=True)),
                ('customer_id', models.TextField(blank=True, null=True)),
                ('start_date', models.TextField(blank=True, null=True)),
                ('frequency', models.TextField(blank=True, null=True)),
                ('priority', models.TextField(blank=True, null=True)),
                ('created_at', gac.models.DateTimeWithoutTZField(default=datetime.datetime.now)),
                ('updated_at', gac.models.DateTimeWithoutTZField(default=datetime.datetime.now)),
                ('id', gac.models.AutoUUIDField(editable=False, primary_key=True, serialize=False)),
                ('job_id', models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, to='etl_job.etljob')),
            ],
            options={
                'db_table': 'airflow"."vendor_customer_raw',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VendorCustomerConform',
            fields=[
                ('vendor_id', models.IntegerField()),
                ('customer_id', models.IntegerField()),
                ('start_date', models.DateField()),
                ('frequency', models.IntegerField()),
                ('priority', models.IntegerField()),
                ('created_at', gac.models.DateTimeWithoutTZField(default=datetime.datetime.now)),
                ('updated_at', gac.models.DateTimeWithoutTZField(default=datetime.datetime.now)),
                ('id', gac.models.AutoUUIDField(editable=False, primary_key=True, serialize=False)),
                ('job_id', models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, to='etl_job.etljob')),
            ],
            options={
                'db_table': 'airflow"."vendor_customer_conform',
                'managed': True,
            },
        ),
    ]
