# Generated by Django 3.2.9 on 2021-12-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorcustomerconform',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vendorcustomerstaged',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
