# Generated by Django 3.2.9 on 2022-01-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_customer', '0002_auto_20211220_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorcustomerconform',
            name='target_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='vendorcustomerstaged',
            name='target_id',
            field=models.TextField(null=True),
        ),
    ]
